export enum ApprovalStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}

export enum ApprovalActionType {
  ESCROW_RELEASE = 'ESCROW_RELEASE',
  DISPUTE_RESOLUTION = 'DISPUTE_RESOLUTION',
  FEE_OVERRIDE = 'FEE_OVERRIDE',
  MANUAL_REFUND = 'MANUAL_REFUND',
  ORGANIZATION_VERIFICATION = 'ORGANIZATION_VERIFICATION',
}
