export enum BloodComponent {
  WHOLE_BLOOD = 'WHOLE_BLOOD',
  RED_CELLS = 'RED_CELLS',
  PLATELETS = 'PLATELETS',
  PLASMA = 'PLASMA',
  CRYOPRECIPITATE = 'CRYOPRECIPITATE',
  WHITE_CELLS = 'WHITE_CELLS',
  FRESH_FROZEN_PLASMA = 'FRESH_FROZEN_PLASMA',
}
