export enum BloodStatus {
  AVAILABLE = 'AVAILABLE',
  RESERVED = 'RESERVED',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
  EXPIRED = 'EXPIRED',
  QUARANTINED = 'QUARANTINED',
  DISCARDED = 'DISCARDED',
  PROCESSING = 'PROCESSING',
}
